In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [4]:
numpy.__version__

'1.20.3'

In [5]:
numpy.NaN

nan

In [7]:
numpy.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
np.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a[0]

array([1, 2, 3, 4])

In [17]:
a[1]

array([5, 6, 7, 8])

In [18]:
a[2]

array([ 9, 10, 11, 12])

In [19]:
np.array([[0,0,0],
         [1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

In [23]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [32]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [35]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [36]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

In [52]:
arr = np.array([[1,2,3,4,5,6,7,8], [5,2,6,2,1,8,3,7]])
arr

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [5, 2, 6, 2, 1, 8, 3, 7]])

In [38]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
x = [1,2]

In [41]:
x.append([3,4])

In [44]:
x

[1, 2, [3, 4]]

In [47]:
np.delete(arr, [4])

array([1, 2, 3, 4, 6, 7, 8])

<module 'numpy' from 'C:\\Users\\adjie\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [53]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 2, 3, 5, 6, 7, 8]])

In [54]:
arr.ndim

2

In [55]:
arr.size

16

In [56]:
arr.shape

(2, 8)

In [58]:
arr = np.array([[[0,1,2,3],
                 [4,5,6,7]],
           
                [[0,1,2,3],
                 [4,5,6,7]],
           
                [[0,1,2,3],
                 [4,5,6,7]]])

In [59]:
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [60]:
arr.ndim

3

In [61]:
arr.size

24

In [62]:
arr.shape

(3, 2, 4)

In [64]:
a = np.arange(6)

In [65]:
a

array([0, 1, 2, 3, 4, 5])

In [77]:
a.reshape(3,-1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
a

array([0, 1, 2, 3, 4, 5])

In [79]:
a.shape

(6,)

In [80]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [81]:
print(a2)

[[0 1 2 3 4 5]]


In [82]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [83]:
col_vector = a[:, np.newaxis]

In [84]:
col_vector.shape

(6, 1)

In [85]:
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [89]:
a

array([1, 2, 3, 4, 5, 6])

In [87]:
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [88]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [90]:
c = np.expand_dims (a, axis = 0)
c.shape

(1, 6)

In [91]:
c

array([[1, 2, 3, 4, 5, 6]])

In [92]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [93]:
data[0]

1

In [94]:
data[1]

2

In [95]:
data[2]

3

In [96]:
data[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [97]:
data[1:]

array([2, 3])

In [98]:
data[-2:]

array([2, 3])

In [100]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [101]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
a.shape

(3, 4)

In [106]:
a.ndim

2

In [108]:
condition = (a>=5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
condition = (a%2==0)
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [111]:
condition = (a>2) & (a<11)
a[condition]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Creating array from existing data

In [113]:
arr = np.array ([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr1 = arr[3:8]

In [115]:
arr1

array([4, 5, 6, 7, 8])

In [118]:
a_1 = np.array([[1,1],[2,2]])
a_2 = np.array([[3,3],[4,4]])

In [119]:
a_1

array([[1, 1],
       [2, 2]])

In [120]:
a_2

array([[3, 3],
       [4, 4]])

In [121]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [122]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [123]:
np.vstack((a_1, a_2)).shape

(4, 2)

In [124]:
np.hstack((a_1, a_2)).shape

(2, 4)

In [126]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
        [13,14,15,16,17,18,19,20,21,22,23,24]])

In [127]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [129]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [131]:
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [132]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [133]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
a.shape

(3, 4)

In [135]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [137]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [138]:
a.sum()

10

In [140]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [144]:
b.sum(axis=1)

array([2, 4])

In [145]:
b.sum(axis=0)

array([3, 3])

In [146]:
data = np.array([1,2])
data

array([1, 2])

In [151]:
ones = np.ones(2)
ones

array([1., 1.])

In [149]:
data + ones

array([2., 3.])

In [150]:
data * ones

array([1., 2.])

In [152]:
data - ones

array([0., 1.])

In [153]:
data / ones

array([1., 2.])

# Broadcasting

In [154]:
data

array([1, 2])

In [155]:
data * 1.6

array([1.6, 3.2])

# More array operations

In [156]:
data.max()

2

In [157]:
data.min()

1

In [158]:
data.sum()

3

# Matrices

In [159]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [160]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [161]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [163]:
np.random.random((3,2))

array([[0.83909855, 0.19727901],
       [0.71924596, 0.70315667],
       [0.45370659, 0.81513645]])

In [165]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [168]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [169]:
data + ones

array([[2., 3.],
       [4., 5.]])

# Dot product

In [170]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [172]:
a_2 = np.array([[7,8],[9,10],[11,12]])
a_2.shape

(3, 2)

In [173]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [175]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [176]:
data [0]

array([1, 2])

In [177]:
data [0,1]

2

In [178]:
data [1:3]

array([[3, 4],
       [5, 6]])

In [179]:
data [0:2, 0]

array([1, 3])

In [180]:
data.max()

6

In [181]:
data.min()

1

In [182]:
data.sum()

21

In [183]:
data.std()

1.707825127659933

In [184]:
data.max(axis = 0)

array([5, 6])

In [185]:
data.max(axis =1)

array([2, 4, 6])

# Transposing and reshaping

In [186]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [187]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [189]:
data_col = np.array([[1,2,3,4,5,6]]).T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [190]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [191]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N-dimensional array

In [201]:
ndarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [202]:
ndarr.shape

(2, 2, 2)

In [203]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Flatten N-Dimensional Array

In [204]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [205]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [206]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [208]:
error  = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'observed' is not defined